steps:
  - id: Download OpenStreetMap data
    name: "gcr.io/cloud-builders/wget"
    args:
      [
        "-q",
        "-O",
        "data.osm.pbf",
        "http://download.geofabrik.de/${_OSM_NAME}-latest.osm.pbf",
      ]
    dir: "data"
  - id: Extract routing graph from OpenStreetMap file
    name: "osrm/osrm-backend"
    args:
      ["osrm-extract", "-p", "${_PROFILE}", "-t", "${_THREADS}", "data.osm.pbf"]
    dir: "data"
  - id: Generate OSRM cell partitions
    name: "osrm/osrm-backend"
    args: ["osrm-partition", "-t", "${_THREADS}", "data.osrm"]
    dir: "data"
  - id: Copy OSRM data files
    name: "osrm/osrm-backend"
    args: ["osrm-customize", "-t", "${_THREADS}", "data.osrm"]
    dir: "data"
artifacts:
  objects:
    location: "${_BUCKET}/osm/${_OSM_NAME}/"
    paths: ["data/*"]
timeout: 10800s
substitutions:
  _BUCKET: "gs://my-bucket-for-storing-routing-data"
  _OSM_NAME: "north-america/us/illinois"
  _THREADS: "8"
  _PROFILE: "/opt/car.lua"
